server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  dubbo:
    application:
      name: gmall-manage-web
    registry:
      address: 10.211.55.5:2181
      protocol: zookeeper
    protocol:
      name: dubbo
    base-package: com.xinxin.gmall
    consumer:
      timeout: 600000
      check: false
#logging:
#  level:
#    root: debug

# tracker 配置文件位置
tracker:
  conf:
    path: /tracker.conf

# 文件下载服务器地址前缀
fileServer:
  url: http://10.211.55.5

