server:
  port: 8071
spring:
  datasource:
    url: jdbc:mysql://10.211.55.5:3306/gmall?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  dubbo:
    protocol:
      name: dubbo
    registry:
      protocol: zookeeper
      address: 10.211.55.5:2181
    base-package: com.xinxin.gmall
    application:
      name: gmall-manage-service
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    root: debug

#logging:
#  level:
#    root: debug





